export const creatorsObjOne = [
    {
        id:1,
        name:'Obinnay Chukwu',
        basicRate:'100',
        premiumRate:'300',
        premiumRate:'300',
        country:'300',
        state:'300',
        overview:'A comedian with a rare ability to captivate your target audience in skits',
        img:'/images/ManImage.svg',
        instagramFollowers:'2000',
        instagramFollowers:'1500',
        youtubeFollowers:'2000',

    },
    {
        id:2,
        name:'Obinnay Chukwu',
        basicRate:'100',
        premiumRate:'300',
        premiumRate:'300',
        country:'300',
        state:'300',
        overview:'A comedian with a rare ability to captivate your target audience in skits',
        img:'/images/ManImage.svg',
        instagramFollowers:'2000',
        instagramFollowers:'1500',
        youtubeFollowers:'2000',

    },
    {
        id:3,
        name:'Obinnay Chukwu',
        basicRate:'100',
        premiumRate:'300',
        premiumRate:'300',
        country:'300',
        state:'300',
        overview:'A comedian with a rare ability to captivate your target audience in skits',
        img:'/images/ManImage.svg',
        instagramFollowers:'2000',
        instagramFollowers:'1500',
        youtubeFollowers:'2000',

    },
    {
        id:4,
        name:'Obinnay Chukwu',
        basicRate:'100',
        premiumRate:'300',
        premiumRate:'300',
        country:'300',
        state:'300',
        overview:'A comedian with a rare ability to captivate your target audience in skits',
        img:'/images/ManImage.svg',
        instagramFollowers:'2000',
        instagramFollowers:'1500',
        youtubeFollowers:'2000',

    },
    {
        id:5,
        name:'Obinnay Chukwu',
        basicRate:'100',
        premiumRate:'300',
        premiumRate:'300',
        country:'300',
        state:'300',
        overview:'A comedian with a rare ability to captivate your target audience in skits',
        img:'/images/ManImage.svg',
        instagramFollowers:'2000',
        instagramFollowers:'1500',
        youtubeFollowers:'2000',

    },
    {
        id:6,
        name:'Obinnay Chukwu',
        basicRate:'100',
        premiumRate:'300',
        premiumRate:'300',
        country:'300',
        state:'300',
        overview:'A comedian with a rare ability to captivate your target audience in skits',
        img:'/images/ManImage.svg',
        instagramFollowers:'2000',
        instagramFollowers:'1500',
        youtubeFollowers:'2000',

    },
    
]