export const creatorsObjOne = [
    {
        id:1,
        name:'Obinnaya Chukwu',
        basicRate:'$100',
        premiumRate:'$300',
        country:'Nigeria',
        city:'Lagos',
        state:'300',
        overview:'A comedian with a rare ability to captivate your target audience in skits',
        img:'/images/ManImage.svg',
        facebookFollowers:'2000',
        instagramFollowers:'1500',
        youtubeFollowers:'2000',

    },
    {
        id:2,
        name:'Obinnaya Chukwu',
        basicRate:'$100',
        premiumRate:'$300',
        country:'Nigeria',
        city:'Lagos',
        state:'300',
        overview:'A comedian with a rare ability to captivate your target audience in skits',
        img:'/images/ManImage.svg',
        facebookFollowers:'2000',
        instagramFollowers:'1500',
        youtubeFollowers:'2000',

    },
    {
        id:3,
        name:'Obinnaya Chukwu',
        basicRate:'$100',
        premiumRate:'$300',
        country:'Nigeria',
        city:'Lagos',
        state:'300',
        overview:'A comedian with a rare ability to captivate your target audience in skits',
        img:'/images/ManImage.svg',
        facebookFollowers:'2000',
        instagramFollowers:'1500',
        youtubeFollowers:'2000',

    },
    {
        id:4,
        name:'Obinnaya Chukwu',
        basicRate:'$100',
        premiumRate:'$300',
        country:'Nigeria',
        city:'Lagos',
        state:'300',
        overview:'A comedian with a rare ability to captivate your target audience in skits',
        img:'/images/ManImage.svg',
        facebookFollowers:'2000',
        instagramFollowers:'1500',
        youtubeFollowers:'2000',

    },
    {
        id:5,
        name:'Obinnaya Chukwu',
        basicRate:'$100',
        premiumRate:'$300',
        country:'Nigeria',
        city:'Lagos',
        state:'300',
        overview:'A comedian with a rare ability to captivate your target audience in skits',
        img:'/images/ManImage.svg',
        facebookFollowers:'2000',
        instagramFollowers:'1500',
        youtubeFollowers:'2000',

    },
    {
        id:6,
        name:'Obinnaya Chukwu',
        basicRate:'$100',
        premiumRate:'$300',
        country:'Nigeria',
        city:'Lagos',
        state:'300',
        overview:'A comedian with a rare ability to captivate your target audience in skits',
        img:'/images/ManImage.svg',
        facebookFollowers:'2000',
        instagramFollowers:'1500',
        youtubeFollowers:'2000',

    },
    
]