export const DashboardInterests = [
    {
        id:1,
        name:'Fashion',
        img:'/images/FashionThumb.jpg',
        alt:'thumbnail interest picture',
        link:'fashion',
        url:'/dashboard/vendor',
        creatorsNum:'2k',  
    },
    {
        id:2,
        name:'Food',
        img:'/images/FoodThumb.jpg',
        alt:'thumbnail interest picture',
        link:'food',
        url:'/dashboard/vendor',
        creatorsNum:'3k',   
    },
    {
        id:3,
        name:'Tech',
        img:'/images/TechThumb.png',
        alt:'thumbnail interest picture',
        link:'tech',
        url:'/dashboard/vendor',
        creatorsNum:'1.5k',   
    },
    {
        id:4,
        name:'Crypto',
        img:'/images/CryptoThumb.jpg',
        alt:'thumbnail interest picture',
        link:'crypto',
        url:'/dashboard/vendor',
        creatorsNum:'1.5k',   
    },
    {
        id:5,
        name:'Automobile',
        img:'/images/AutoThumb.jpg',
        alt:'thumbnail interest picture',
        link:'auto',
        url:'/dashboard/vendor',
        creatorsNum:'1.5k',   
    },
    {
        id:6,
        name:'Arts',
        img:'/images/ArtsThumb.png',
        alt:'thumbnail interest picture',
        link:'arts',
        url:'/dashboard/vendor',
        creatorsNum:'1.5k',   
    },
    
]